package org.gatherdata.archiver.dao.el.internal;

import org.eclipse.persistence.sessions.*;
import org.eclipse.persistence.tools.schemaframework.*;

/**
 * This class was generated by the TopLink table creator generator.
 * It stores the meta-data (tables) that define the database schema.
 * @see org.eclipse.persistence.sessions.factories.TableCreatorClassGenerator
 */

public class EnvelopeArchiveTableCreator extends org.eclipse.persistence.tools.schemaframework.TableCreator {

public EnvelopeArchiveTableCreator() {
	setName("GatherArchiver");
	
	addTableDefinition(buildENVELOPEDTOTable());
}

public TableDefinition buildENVELOPEDTOTable() {
	TableDefinition table = new TableDefinition();
	table.setName("ENVELOPEDTO");
	
	FieldDefinition fieldALGORITHM = new FieldDefinition();
	fieldALGORITHM.setName("ALGORITHM");
	fieldALGORITHM.setTypeName("VARCHAR");
	fieldALGORITHM.setSize(0);
	fieldALGORITHM.setSubSize(0);
	fieldALGORITHM.setIsPrimaryKey(false);
	fieldALGORITHM.setIsIdentity(false);
	fieldALGORITHM.setUnique(false);
	fieldALGORITHM.setShouldAllowNull(true);
	table.addField(fieldALGORITHM);
	
	FieldDefinition fieldCONTENTS = new FieldDefinition();
	fieldCONTENTS.setName("CONTENTS");
	fieldCONTENTS.setTypeName("BINARY");
	fieldCONTENTS.setSize(0);
	fieldCONTENTS.setSubSize(0);
	fieldCONTENTS.setIsPrimaryKey(false);
	fieldCONTENTS.setIsIdentity(false);
	fieldCONTENTS.setUnique(false);
	fieldCONTENTS.setShouldAllowNull(true);
	table.addField(fieldCONTENTS);
	
	FieldDefinition fieldDATE_TIME_STAMP = new FieldDefinition();
	fieldDATE_TIME_STAMP.setName("DATE_TIME_STAMP");
	fieldDATE_TIME_STAMP.setTypeName("TIMESTAMP");
	fieldDATE_TIME_STAMP.setSize(0);
	fieldDATE_TIME_STAMP.setSubSize(0);
	fieldDATE_TIME_STAMP.setIsPrimaryKey(false);
	fieldDATE_TIME_STAMP.setIsIdentity(false);
	fieldDATE_TIME_STAMP.setUnique(false);
	fieldDATE_TIME_STAMP.setShouldAllowNull(true);
	table.addField(fieldDATE_TIME_STAMP);
	
	FieldDefinition fieldDIGEST = new FieldDefinition();
	fieldDIGEST.setName("DIGEST");
	fieldDIGEST.setTypeName("VARCHAR");
	fieldDIGEST.setSize(0);
	fieldDIGEST.setSubSize(0);
	fieldDIGEST.setIsPrimaryKey(false);
	fieldDIGEST.setIsIdentity(false);
	fieldDIGEST.setUnique(false);
	fieldDIGEST.setShouldAllowNull(true);
	table.addField(fieldDIGEST);
	
	FieldDefinition fieldID = new FieldDefinition();
	fieldID.setName("ID");
	fieldID.setTypeName("INTEGER");
	fieldID.setSize(0);
	fieldID.setSubSize(0);
	fieldID.setIsPrimaryKey(true);
	fieldID.setIsIdentity(false);
	fieldID.setUnique(false);
	fieldID.setShouldAllowNull(false);
	table.addField(fieldID);
	
	FieldDefinition fieldMIME_TYPE = new FieldDefinition();
	fieldMIME_TYPE.setName("MIME_TYPE");
	fieldMIME_TYPE.setTypeName("VARCHAR");
	fieldMIME_TYPE.setSize(0);
	fieldMIME_TYPE.setSubSize(0);
	fieldMIME_TYPE.setIsPrimaryKey(false);
	fieldMIME_TYPE.setIsIdentity(false);
	fieldMIME_TYPE.setUnique(false);
	fieldMIME_TYPE.setShouldAllowNull(true);
	table.addField(fieldMIME_TYPE);
	
	FieldDefinition fieldQUALIFIER = new FieldDefinition();
	fieldQUALIFIER.setName("QUALIFIER");
	fieldQUALIFIER.setTypeName("VARCHAR");
	fieldQUALIFIER.setSize(0);
	fieldQUALIFIER.setSubSize(0);
	fieldQUALIFIER.setIsPrimaryKey(false);
	fieldQUALIFIER.setIsIdentity(false);
	fieldQUALIFIER.setUnique(false);
	fieldQUALIFIER.setShouldAllowNull(true);
	table.addField(fieldQUALIFIER);
	
	FieldDefinition fieldSOURCE_URI = new FieldDefinition();
	fieldSOURCE_URI.setName("SOURCE_URI");
	fieldSOURCE_URI.setTypeName("VARCHAR");
	fieldSOURCE_URI.setSize(0);
	fieldSOURCE_URI.setSubSize(0);
	fieldSOURCE_URI.setIsPrimaryKey(false);
	fieldSOURCE_URI.setIsIdentity(false);
	fieldSOURCE_URI.setUnique(false);
	fieldSOURCE_URI.setShouldAllowNull(true);
	table.addField(fieldSOURCE_URI);
	
	FieldDefinition fieldUID_URI = new FieldDefinition();
	fieldUID_URI.setName("UID_URI");
	fieldUID_URI.setTypeName("VARCHAR");
	fieldUID_URI.setSize(0);
	fieldUID_URI.setSubSize(0);
	fieldUID_URI.setIsPrimaryKey(true);
	fieldUID_URI.setIsIdentity(false);
	fieldUID_URI.setUnique(false);
	fieldUID_URI.setShouldAllowNull(false);
	table.addField(fieldUID_URI);
	
	return table;
}

}
